server:
  port: 8761

spring:
  application:
    name: EUREKA-CLOUD-SERVER
  cloud:
    config:
      enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
